apiVersion: v1
kind: Service
metadata:
  name: news-aggregator-service
spec:
  selector:
    app: news-aggregator
  ports:
    - protocol: TCP
      port: 80          # Port exposed on your localhost
      targetPort: 8000  # The actual app port inside the container
      nodePort: 30080   # Fixed node port for accessing via localhost
  type: NodePort
